[package]
name = "cmd-utils"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
